import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://practicesoftwaretesting.com/auth/register');
  await page.locator('[data-test="first-name"]').click();
  await page.locator('[data-test="first-name"]').fill('test');
  await page.locator('[data-test="last-name"]').click();
  await page.locator('[data-test="last-name"]').fill('test');
  await page.locator('[data-test="dob"]').click();
  await page.locator('[data-test="dob"]').fill('1990-08-23');
  await page.locator('[data-test="dob"]').press('Enter');
  await page.locator('[data-test="dob"]').press('Tab');
  await page.locator('[data-test="street"]').fill('test street');
  await page.locator('[data-test="postal_code"]').click();
  await page.locator('[data-test="postal_code"]').fill('1`23');
  await page.locator('[data-test="postal_code"]').press('ArrowLeft');
  await page.locator('[data-test="postal_code"]').press('ArrowLeft');
  await page.locator('[data-test="postal_code"]').fill('123');
  await page.locator('[data-test="postal_code"]').press('ArrowRight');
  await page.locator('[data-test="postal_code"]').press('ArrowRight');
  await page.locator('[data-test="postal_code"]').press('Enter');
  await page.locator('[data-test="city"]').click();
  await page.locator('[data-test="city"]').fill('test');
  await page.locator('[data-test="state"]').click();
  await page.locator('[data-test="state"]').fill('test');
  await page.locator('[data-test="country"]').selectOption('AU');
  await page.locator('[data-test="phone"]').click();
  await page.locator('[data-test="phone"]').fill('094342342');
  await page.locator('[data-test="email"]').click();
  await page.locator('[data-test="email"]').fill('test@gmail.com');
  await page.locator('[data-test="password"]').click();
  await page.locator('[data-test="password"]').fill('Password!2');
  await page.locator('[data-test="register-submit"]').click();
});